<?php

use Illuminate\Database\Seeder;

class MenuTextSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $data = [
            ['menu_id' => '1', 'lang' => 'rus', 'text' => 'Шея'],
            ['menu_id' => '1', 'lang' => 'eng', 'text' => 'Neck'],
            ['menu_id' => '1', 'lang' => 'deu', 'text' => 'Hals'],
            ['menu_id' => '1', 'lang' => 'spa', 'text' => 'Cuello'],
            ['menu_id' => '1', 'lang' => 'por', 'text' => 'Pescoço'],
            ['menu_id' => '2', 'lang' => 'rus', 'text' => 'Плечи'],
            ['menu_id' => '2', 'lang' => 'eng', 'text' => 'Shoulders'],
            ['menu_id' => '2', 'lang' => 'deu', 'text' => 'Schultern'],
            ['menu_id' => '2', 'lang' => 'spa', 'text' => 'Hombros'],
            ['menu_id' => '2', 'lang' => 'por', 'text' => 'Ombros'],
            ['menu_id' => '3', 'lang' => 'rus', 'text' => 'Грудь'],
            ['menu_id' => '3', 'lang' => 'eng', 'text' => 'Chest'],
            ['menu_id' => '3', 'lang' => 'deu', 'text' => 'Brust'],
            ['menu_id' => '3', 'lang' => 'spa', 'text' => 'Pecho'],
            ['menu_id' => '3', 'lang' => 'por', 'text' => 'Peito'],
            ['menu_id' => '4', 'lang' => 'rus', 'text' => 'Бицепс'],
            ['menu_id' => '4', 'lang' => 'eng', 'text' => 'Biceps'],
            ['menu_id' => '4', 'lang' => 'deu', 'text' => 'Bizeps'],
            ['menu_id' => '4', 'lang' => 'spa', 'text' => 'Bíceps'],
            ['menu_id' => '4', 'lang' => 'por', 'text' => 'Bíceps'],
            ['menu_id' => '5', 'lang' => 'rus', 'text' => 'Пресс'],
            ['menu_id' => '5', 'lang' => 'eng', 'text' => 'Abdominal Muscles'],
            ['menu_id' => '5', 'lang' => 'deu', 'text' => 'Bauchmuskulatur'],
            ['menu_id' => '5', 'lang' => 'spa', 'text' => 'Musculos Abdominales'],
            ['menu_id' => '5', 'lang' => 'por', 'text' => 'Músculos abdominais'],
            ['menu_id' => '7', 'lang' => 'rus', 'text' => 'Трапеции'],
            ['menu_id' => '7', 'lang' => 'eng', 'text' => 'Traps'],
            ['menu_id' => '7', 'lang' => 'deu', 'text' => 'Trapezmuskel'],
            ['menu_id' => '7', 'lang' => 'spa', 'text' => 'Trapecio'],
            ['menu_id' => '7', 'lang' => 'por', 'text' => 'Trapézio'],
            ['menu_id' => '9', 'lang' => 'rus', 'text' => 'Трицепс'],
            ['menu_id' => '9', 'lang' => 'eng', 'text' => 'Triceps'],
            ['menu_id' => '9', 'lang' => 'deu', 'text' => 'Trizeps'],
            ['menu_id' => '9', 'lang' => 'spa', 'text' => 'Tríceps'],
            ['menu_id' => '9', 'lang' => 'por', 'text' => 'Tríceps'],
            ['menu_id' => '10', 'lang' => 'rus', 'text' => 'Ягодицы'],
            ['menu_id' => '10', 'lang' => 'eng', 'text' => 'Glutes'],
            ['menu_id' => '10', 'lang' => 'deu', 'text' => 'Gesäß'],
            ['menu_id' => '10', 'lang' => 'spa', 'text' => 'Glúteos'],
            ['menu_id' => '10', 'lang' => 'por', 'text' => 'Glúteos'],
            ['menu_id' => '11', 'lang' => 'rus', 'text' => 'Квадрицепс'],
            ['menu_id' => '11', 'lang' => 'eng', 'text' => 'Quadriceps'],
            ['menu_id' => '11', 'lang' => 'deu', 'text' => 'Quadrizeps'],
            ['menu_id' => '11', 'lang' => 'spa', 'text' => 'Cuadríceps'],
            ['menu_id' => '11', 'lang' => 'por', 'text' => 'Quadríceps'],
            ['menu_id' => '12', 'lang' => 'rus', 'text' => 'Бицепс бедра'],
            ['menu_id' => '12', 'lang' => 'eng', 'text' => 'Hamstring'],
            ['menu_id' => '12', 'lang' => 'deu', 'text' => 'Beinbizeps'],
            ['menu_id' => '12', 'lang' => 'spa', 'text' => 'Isquiotibiales'],
            ['menu_id' => '12', 'lang' => 'por', 'text' => 'Isquiossurais'],
            ['menu_id' => '13', 'lang' => 'rus', 'text' => 'Икры'],
            ['menu_id' => '13', 'lang' => 'eng', 'text' => 'Calf Muscle'],
            ['menu_id' => '13', 'lang' => 'deu', 'text' => 'Unterschenkelmuskel'],
            ['menu_id' => '13', 'lang' => 'spa', 'text' => 'Músculos Pantorrilla'],
            ['menu_id' => '13', 'lang' => 'por', 'text' => 'Panturrilha'],
            ['menu_id' => '14', 'lang' => 'rus', 'text' => 'Предплечья'],
            ['menu_id' => '14', 'lang' => 'eng', 'text' => 'Forearms'],
            ['menu_id' => '14', 'lang' => 'deu', 'text' => 'Unterarme'],
            ['menu_id' => '14', 'lang' => 'spa', 'text' => 'Antebrazos'],
            ['menu_id' => '14', 'lang' => 'por', 'text' => 'Antebraços'],
            ['menu_id' => '15', 'lang' => 'rus', 'text' => 'Кардио упражнения'],
            ['menu_id' => '15', 'lang' => 'eng', 'text' => 'Cardio Exercises'],
            ['menu_id' => '15', 'lang' => 'deu', 'text' => 'Herz-Kreislauf-Training'],
            ['menu_id' => '15', 'lang' => 'spa', 'text' => 'Ejercicios de Cardio'],
            ['menu_id' => '15', 'lang' => 'por', 'text' => 'Exercícios de Cardio'],
            ['menu_id' => '16', 'lang' => 'rus', 'text' => 'Широчайшие'],
            ['menu_id' => '16', 'lang' => 'eng', 'text' => 'Lats'],
            ['menu_id' => '16', 'lang' => 'deu', 'text' => 'Breiteste'],
            ['menu_id' => '16', 'lang' => 'spa', 'text' => 'Dorsales'],
            ['menu_id' => '16', 'lang' => 'por', 'text' => 'Grande dorsal'],
            ['menu_id' => '17', 'lang' => 'rus', 'text' => 'Разгибатели спины'],
            ['menu_id' => '17', 'lang' => 'eng', 'text' => 'Back Extensors'],
            ['menu_id' => '17', 'lang' => 'deu', 'text' => 'Rückenstrecker'],
            ['menu_id' => '17', 'lang' => 'spa', 'text' => 'Dorsal (Ancho]'],
            ['menu_id' => '17', 'lang' => 'por', 'text' => 'Lombar'],
            ['menu_id' => '18', 'lang' => 'rus', 'text' => 'Растяжка'],
            ['menu_id' => '18', 'lang' => 'eng', 'text' => 'Stretching'],
            ['menu_id' => '18', 'lang' => 'deu', 'text' => 'Dehnen'],
            ['menu_id' => '18', 'lang' => 'spa', 'text' => 'Estiramientos'],
            ['menu_id' => '18', 'lang' => 'por', 'text' => 'Alongamento'],
            ['menu_id' => '19', 'lang' => 'rus', 'text' => 'Берпи'],
            ['menu_id' => '19', 'lang' => 'eng', 'text' => 'Burpee'],
            ['menu_id' => '19', 'lang' => 'deu', 'text' => 'Burpee'],
            ['menu_id' => '19', 'lang' => 'spa', 'text' => 'Burpee'],
            ['menu_id' => '19', 'lang' => 'por', 'text' => 'Burpee'],
            ['menu_id' => '20', 'lang' => 'rus', 'text' => 'Плавание'],
            ['menu_id' => '20', 'lang' => 'eng', 'text' => 'Swimming'],
            ['menu_id' => '20', 'lang' => 'deu', 'text' => 'Schwimmen'],
            ['menu_id' => '20', 'lang' => 'spa', 'text' => 'Natación'],
            ['menu_id' => '20', 'lang' => 'por', 'text' => 'Natação'],

        ];
        DB::table('sport_menu_texts')->insert($data);
    }
}
